
[collector.pipeline]
browser = "chromium"

[collector.pipeline.browser_params]
headless = false

[[collector.pipeline.steps]]

[collector.pipeline.steps.config]
timeout = 1500
nav_timeout = 1500

[[collector.pipeline.steps]]
goto = "https://khamooshi.maztozi.ir/"

[[collector.pipeline.steps]]
sleep = "1s"

[[collector.pipeline.steps]]
loop = """
{{ eval `JSON.stringify(
  [...document.querySelectorAll('#ContentPlaceHolder1_ddlCity > option')]
  .map((a) =>  a.getAttribute('value'))
  .filter((a) => a!='-1' )
  )`
}}"""
loop-key = "addr"
on-error = "ignore"

[[collector.pipeline.steps.steps]]
goto = "https://khamooshi.maztozi.ir/"

[[collector.pipeline.steps.steps]]
click = "#ContentPlaceHolder1_rbIsAddress"

[[collector.pipeline.steps.steps]]
sleep = "50ms"

[[collector.pipeline.steps.steps]]
click = "#ContentPlaceHolder1_ddlCity"

[[collector.pipeline.steps.steps]]
select = "#ContentPlaceHolder1_ddlCity"
values = "{{ addr }}"
on-error = "ignore"

[[collector.pipeline.steps.steps]]
sleep = "50ms"

[[collector.pipeline.steps.steps]]
click = "#ContentPlaceHolder1_btnSearchOutage"

[[collector.pipeline.steps.steps]]
element = "#ContentPlaceHolder1_grdOutages"
on-error = "ignore"
mode = "table"
set-var = '{{ eval "ContentPlaceHolder1_ddlCity.selectedOptions[0].text" }}'

# [[collector.pipeline.steps]]
# loop = """
# {{ eval `JSON.stringify(
#   [...document.querySelectorAll('#ContentPlaceHolder1_ddlCity > option')]
#   .map((a) =>  a.getAttribute('value'))
#   .filter((a) => a!='-1' )
#   )`
# }}"""
# loop-key = "city"
# on-error = "ignore"

# [[collector.pipeline.steps.steps]]
# goto = "https://khamooshi.maztozi.ir/"

# [[collector.pipeline.steps.steps]]
# click = "#ContentPlaceHolder1_rbIsAddress"

# [[collector.pipeline.steps.steps]]
# click = "#ContentPlaceHolder1_ddlCity"

# [[collector.pipeline.steps.steps]]
# select = "#ContentPlaceHolder1_ddlCity"
# values = "{{ city }}"
# on-error = "ignore"

# [[collector.pipeline.steps.steps]]
# sleep = "1s"

# [[collector.pipeline.steps.steps]]
# nop = """
# {{ eval `[...document.querySelectorAll('#ContentPlaceHolder1_ddlArea > option')]
#   .map((a) =>  a.innerText)
#   .filter((a) => !a.startsWith("--") )
#   .join(",")`
# }}"""
# set-var = 'map.{{ eval "ContentPlaceHolder1_ddlCity.selectedOptions[0].text" }}'
